services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html

    app:
        build:
            context: ./docker/php
            target: base
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "client_host=host.docker.internal xdebug.idekey=PHPSTORM"
        volumes:
            - ./:/var/www/html

    mariadb:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - 3306:3306

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "1025:1025"   # SMTP port
            - "8025:8025"   # Web UI
volumes:
    mariadb:
        name: ${DB_VOLUME_NAME:-db-mariadb}
