controllers:
    resource: ../../src/Controller/
    type: attribute

api_controllers:
    resource: ../../src/Controller/Api
    type: attribute
    prefix: api

kernel:
    resource: ../../src/Kernel.php
    type: attribute
