name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            -   name: Checkout code
                uses: actions/checkout@v3

            # Log in to the private Docker registry
            -   name: Log in to Docker registry
                uses: docker/login-action@v2
                env:
                    DOCKER_CLI_DEBUG: 1
                with:
                    registry: registry.tom-hart.net
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}

            # Build the Docker image
            -   name: Build Docker image
                run: |
                    docker build -f ./docker/php/Dockerfile -t registry.tom-hart.net/${{ github.repository }}:latest .

            # Push the Docker image to the private registry
            -   name: Push Docker image
                run: |
                    docker push registry.tom-hart.net/${{ github.repository }}:latest