name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            -   name: Checkout code
                uses: actions/checkout@v3

            # Log in to the private Docker registry
            -   name: Log in to Docker registry
                uses: docker/login-action@v2
                with:
                    registry: registry.tom-hart.net
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}



            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./docker/php/Dockerfile
                    push: true
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    tags: registry.tom-hart.net/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest

#            # Build the Docker image
#            -   name: Build Docker image
#                run: |
#                    REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
#                    docker build -f ./docker/php/Dockerfile -t registry.tom-hart.net/${REPO_NAME}:latest .
#
#            # Push the Docker image to the private registry
#            -   name: Push Docker image
#                run: |
#                    REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
#                    docker push registry.tom-hart.net/${REPO_NAME}:latest